# Generated by Django 3.2.8 on 2021-10-27 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='skill',
            new_name='skills',
        ),
    ]
